/*
 * This file is generated by jOOQ.
 */
package com.uianz;


import com.uianz.tables.Author;
import com.uianz.tables.Book;


/**
 * Convenience access to all tables in R2DBC_EXAMPLE.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>R2DBC_EXAMPLE.AUTHOR</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>R2DBC_EXAMPLE.BOOK</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
